# Site settings
title: LACS Development Playbook
name: LACS Development Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: LACS Guidance
baseurl: '/ficam-lacs'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: rouge
branch: master

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-lacs/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: program-guides
  description: FICAM Playbook - Streamline Identity Management
  url: https://github.com/gsa/ficam-identity

# Build settings
markdown: kramdown


exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Home
  url: index.html
  internal: true
  coll: false
- text: Step 1 - Identify Common Logical Access Scenarios
  url: 1_step-1
  internal: true
  coll: false
- text: Step 2 - Plan
  url: 2_step-2
  internal: true
  coll: false
- text: Step 3 - Design
  url: 3_step-3
  internal: true
  coll: false
- text: Step 4 - Build
  url: 4_step-4
  internal: true
  coll: false
- text: Step 5 - Implement
  url: 5_step-5
  internal: true
  coll: false
- text: Step 6 - Operate and Maintain
  url: 6_step-6
  internal: true
- text: Contribute
  url: contribute
  internal: true
include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
